version: '3.8'
services:
  database:
    image: mysql/mysql-server:8.0
    container_name: 'social_db'
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: 'social'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

  social:
    image: social:latest
    restart: on-failure
    build:
      context: ./social
      dockerfile: Dockerfile
    depends_on:
      - database
    ports:
      - "8080:8080"
    environment:
      - DATABASE_HOST=database



