CREATE TABLE IF NOT EXISTS users (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
     username VARCHAR(50)  UNIQUE NOT NULL,
     password VARCHAR(255) NOT NULL,
     first_name  VARCHAR(255),
     last_name  VARCHAR(255),
     age  SMALLINT,
     gender SMALLINT check (gender between 0 and 1) NOT NULL,
     interest TEXT,
     city VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS friends (
    friend_1 BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    friend_2 BIGINT REFERENCES users (id) NOT NULL,
    CONSTRAINT pk_fiends PRIMARY KEY (friend_1, friend_2)
);

CREATE TABLE IF NOT EXISTS posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    "user_id" BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT now()
);

CREATE TABLE IF NOT EXISTS feeds (
    "user_id" BIGINT REFERENCES users (id) ON DELETE CASCADE NOT NULL,
    "post_id" BIGINT REFERENCES posts (id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE IF NOT EXISTS dialogs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "key_id" VARCHAR NOT NULL,
    "from" BIGINT  NOT NULL,
    "to" BIGINT  NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT now()
);

CREATE INDEX IF NOT EXISTS "key_id" ON dialogs ("key_id")

--SELECT create_distributed_table('dialogs', 'key_id');
