CREATE TABLE IF NOT EXISTS users (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
     username VARCHAR(50)  UNIQUE NOT NULL,
     password VARCHAR(255) NOT NULL,
     first_name  VARCHAR(255),
     last_name  VARCHAR(255),
     age  SMALLINT,
     gender SMALLINT check (gender between 0 and 1) NOT NULL,
     interest TEXT,
     city VARCHAR(100)
);